name: C/C++ CI

on:
  push:
    paths:
    - "data/userData.json"

jobs:
  update:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        repository: hjenryin/BCJH-Metropolis
    - name: commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with: 
        commit_message: 自动拉取最新更新
        file_pattern: "^data/data.min.json"
        branch: ${{ github.ref_name }}
        skip_dirty_check: false
      
    
    # - name: update
    #   run: python3 data/checkUpdate.py
    # - name: commit
    #   uses: stefanzweifel/git-auto-commit-action@v4
    #   with: 
    #     commit_message: 自动拉取图鉴网数据
    #     file_pattern: "data/data.min.json"
    #     skip_dirty_check: false
  buildTest:
    runs-on: ubuntu-latest
    needs: update
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: if [ -f data/userData.json ];then mkdir build && cd ./build && cmake .. && make -j$(nproc);fi
    - name: run
      run: if [ -f data/userData.json ];then cd ./build && ./bcjh -s && ./bcjh -s;else echo $error ;fi 
      env:
        error: "个人文件不存在。"

